apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  labels:
    app: yolo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: docker.io/machoyamwangi/yolo-frontend:v1.0.1
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://yolo-backend-service:5000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
  labels:
    app: yolo-frontend
spec:
  selector:
    app: yolo-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: LoadBalancer
